-- 삽입/삭제/수정하면 메세지를 출력하는 트리거 만들기

SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER MY_TRIGGER
-- AFTER, DEFAULT..? 연습
    AFTER
    INSERT OR DELETE OR UPDATE -- 1개~3개 중 선택 적용 가능
    ON DEPARTMENT_TBL
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('하하하하카');
END;

INSERT INTO DEPARTMENT_TBL(DEPT_NO, DEPT_NAME, LOCATION) VALUES(7, '영업부', '서울');